**Experiment - 1**

Fundamentals of tensor using pytorch and numpy.

In [1]:
import numpy as np
import torch

In [2]:
print("Numpy Version : ",np.__version__)
print("PyTorch Version : ",np.__version__)

Numpy Version :  2.0.2
PyTorch Version :  2.0.2


**Why tensors ?**

Comparision between list and tensors.

In [3]:
import time
n=10000

a=list(range(n))
b=list(range(n))

t1=torch.arange(n)
t2=torch.arange(n)

start =time.time()
for i in range(n):
  a[i]*b[i]
end = time.time()
print("Using List : ",end-start)

start=time.time()
t1*t2
end = time.time()
print("Using tensors : ",end-start)


Using List :  0.0033795833587646484
Using tensors :  0.03445887565612793


1D , 2D and 3D array using numpy.

In [14]:
n_1d = np.array([1,3,4])
n_2d = np.array([[11,12,13],[4,5,6]])
n_3d = np.array([[[1,2,3],[4,5,6]],[[12,12,23],[45,56,67]]])

print(n_1d)
print(" ")
print(n_2d)
print(" ")
print(n_3d)

[1 3 4]
 
[[11 12 13]
 [ 4  5  6]]
 
[[[ 1  2  3]
  [ 4  5  6]]

 [[12 12 23]
  [45 56 67]]]


1D , 2D and 3D tensors using Pytorch.

In [15]:
t_1d = torch.tensor([1,3,4])
t_2d = torch.tensor([[11,12,13],[4,5,6]])
t_3d = torch.tensor([[[1,2,3],[4,5,6]],[[12,12,23],[45,56,67]]])

print(t_1d)
print(" ")
print(t_2d)
print(" ")
print(t_3d)

tensor([1, 3, 4])
 
tensor([[11, 12, 13],
        [ 4,  5,  6]])
 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[12, 12, 23],
         [45, 56, 67]]])


Element wise operation using tensors.

In [16]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print("Addition : ",a+b)
print("Subtraction : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)

Addition :  tensor([5, 7, 9])
Subtraction :  tensor([-3, -3, -3])
Multiplication :  tensor([ 4, 10, 18])
Division :  tensor([0.2500, 0.4000, 0.5000])


Element wise operation using numpy array.

In [17]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])
print("Addition : ",a_np+b_np)
print("Subtraction : ",a_np-b_np)
print("Multiplication : ",a_np*b_np)
print("Division : ",a_np/b_np)

Addition :  [5 7 9]
Subtraction :  [-3 -3 -3]
Multiplication :  [ 4 10 18]
Division :  [0.25 0.4  0.5 ]


Indexing , Slicing operations in tensors.

In [8]:
print("Indexing")
x = torch.tensor([[11,12,13],[14,15,16]])
print(x[0])
print(x[:,2])
print(x[1,2])

Indexing
tensor([11, 12, 13])
tensor([13, 16])
tensor(16)


In [9]:
print("Extracting Sub-tensors")
print(x[0:2,1:3])

print("Boolean Masking")
y = torch.tensor([1,2,3,4,5])

mask = y>2
print(mask)
print(y[mask])
y_np = np.array([1,2,3,4,5])
print(y[y>2])

Extracting Sub-tensors
tensor([[12, 13],
        [15, 16]])
Boolean Masking
tensor([False, False,  True,  True,  True])
tensor([3, 4, 5])
tensor([3, 4, 5])


.view , .reshape , .unsqueeze and squeeze function in pytorch.

In [10]:
#.view()
t = torch.arange(12)
print(t)

t2 = t.view(3, 4)
print(t2)

#.reshape()
t3 = t.reshape(4, 3)
print(t3)

#.unsqueeze()
a = torch.tensor([1, 2, 3])
print(a.shape)

b = a.unsqueeze(0)
print(b.shape)

c = a.unsqueeze(1)
print(c.shape)

#.squeeze()
d = torch.tensor([[1, 2, 3]])
print(d.shape)

print(d.squeeze().shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([1, 3])
torch.Size([3])


.reshape in numpy

In [11]:
np_arr = np.arange(12)
np_reshaped = np_arr.reshape(3, 4)
print(np_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Broadcasting in tensors

In [18]:
print("pytorch")
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = torch.tensor([10, 20, 30])

print(x + y)

print("numpy")
x_np = np.array([[1, 2, 3],
                 [4, 5, 6]])

y_np = np.array([10, 20, 30])

print(x_np + y_np)

pytorch
tensor([[11, 22, 33],
        [14, 25, 36]])
numpy
[[11 22 33]
 [14 25 36]]


In place vs out of place operations

In [19]:
#out of place operations
a = torch.tensor([1, 2, 3])
b = a + 5

print(a)
print(b)

#in of place operations
a = torch.tensor([1, 2, 3])
a.add_(5)

print(a)

tensor([1, 2, 3])
tensor([6, 7, 8])
tensor([6, 7, 8])
